// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace VuQuangKhai0323.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    [Migration("20230623014533_VQKLophoc")]
    partial class VQKLophoc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("VuQuangKhai0323.Models.VQKLophoc", b =>
                {
                    b.Property<string>("VQKTenlop")
                        .HasColumnType("TEXT");

                    b.Property<string>("VQKMalop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VQKTenlop");

                    b.HasIndex("VQKMalop");

                    b.ToTable("VQKLophoc");
                });

            modelBuilder.Entity("VuQuangKhai0323.Models.VQKSinhvien", b =>
                {
                    b.Property<string>("VQKMasinhvien")
                        .HasColumnType("TEXT");

                    b.Property<string>("VQKHoten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VQKMalop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VQKMasinhvien");

                    b.ToTable("VQKSinhvien");
                });

            modelBuilder.Entity("VuQuangKhai0323.Models.VQKLophoc", b =>
                {
                    b.HasOne("VuQuangKhai0323.Models.VQKSinhvien", "VQKSinhvien")
                        .WithMany()
                        .HasForeignKey("VQKMalop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VQKSinhvien");
                });
#pragma warning restore 612, 618
        }
    }
}
