// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace VuQuangKhai0323.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    partial class MvcMovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("VuQuangKhai0323.Models.VQKSinhvien", b =>
                {
                    b.Property<string>("VQKMasinhvien")
                        .HasColumnType("TEXT");

                    b.Property<string>("VQKHoten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VQKMalop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VQKMasinhvien");

                    b.ToTable("VQKSinhvien");
                });
#pragma warning restore 612, 618
        }
    }
}
